name: Pandemonium API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build
        run: go build -v

      - name: Run tests
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Tailscale
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}  # Use the auth key to connect

      # Ensure Tailscale is connected before proceeding
      - name: Verify Tailscale connection
        run: |
          sudo tailscale status

      # Deploy to Server via SSH (Tailscale)
      - name: Deploy to Server via SSH (Tailscale)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}  # Use the Tailscale IP of your server
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/pandemonium_api
            git pull origin main
            go build -o pandemonium_api
            pm2 restart myapi || pm2 start myapi --name pandemonium_api
